---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: vote-app-pipeline
  namespace: {{ .Values.tektonNamespace }}
spec:
  params:
  - name: SOURCE_GIT_URL
    type: string
    description: The application git repository url
    default: {{ .Values.app.repo.source.url }}
  - name: SOURCE_GIT_REVISION
    type: string
    default: {{ .Values.app.repo.source.revision }}
    description: The application git repository revision
  - default: image-registry.openshift-image-registry.svc:5000/{{ .Values.app.namespace }}/vote-api:latest
    name: IMAGE_NAME
    type: string
  - default: .
    name: PATH_CONTEXT
    type: string

  workspaces:
  - name: app-source

  tasks:

  - name: git-clone
    taskRef:
      kind: ClusterTask
      name: git-clone
    params:
    - name: url
      value: $(params.SOURCE_GIT_URL)
    - name: revision
      value: $(params.SOURCE_GIT_REVISION)
    - name: deleteExisting
      value: 'true'
    workspaces:
    - name: output
      workspace: app-source

  - name: build-and-push
    params:
    - name: IMAGE
      value: $(params.IMAGE_NAME)
    - name: TLSVERIFY
      value: "false"
    - name: CONTEXT
      value: $(params.PATH_CONTEXT)
    runAfter:
    - git-clone
    taskRef:
      kind: ClusterTask
      name: buildah
    workspaces:
    - name: output
      workspace: app-source
