---
apiVersion: v1
kind: Secret
metadata:
  name: gitea-source
  namespace: {{ .Values.tektonNamespace }}
  annotations:
    tekton.dev/git-0: {{ .Values.app.repo.source.url }}
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.app.repo.source.user }}
  password: {{ .Values.app.repo.source.password }}
---
apiVersion: v1
kind: Secret
metadata:
  name: gitea-gitops
  namespace: {{ .Values.tektonNamespace }}
  annotations:
    tekton.dev/git-0: {{ .Values.app.repo.gitops.url }}
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.app.repo.gitops.user }}
  password: {{ .Values.app.repo.gitops.password }}
