---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: eventlistener
  namespace: {{ .Values.tektonNamespace }}
spec:
  serviceAccountName: pipeline
  triggers:
  - name: gitea-vote-app-pipeline
    bindings:
    - ref: gitea
    template:
      ref: vote-app-pipeline
