apiVersion: v1
kind: Secret
metadata:
  name: git-credentials
  namespace: {{ .Values.namespace }}
  annotations:
    controller.devfile.io/mount-path: /tmp/.git-credentials/
  labels:
    controller.devfile.io/git-credential: "true"
    controller.devfile.io/watch-secret: "true"
type: Opaque
stringData:
  credentials: {{ .Values.user }}:openshift@{{ .Values.app.repo.ui.url }}