apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../k8s/
patchesJson6902:
- patch: |-
    - op: add
      path: /metadata/annotations
      value:
        argocd.argoproj.io/sync-wave: "0"
  target:
    group: apps
    kind: Deployment
    name: vote-api
    version: v1