apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../k8s/
patchesJson6902:
- patch: |-
    - op: add
      path: /metadata/annotations
      value:
        app.openshift.io/vcs-uri: 'https://github.com/blues-man/pipelines-vote-ui.git'
        app.openshift.io/vcs-ref: 'master'